Разметка
htmlacademy-htmlcss/1773559-sedona-31 pull request #1
Opened 2021-05-21 13:02 UTC by Ramz10

2021-05-21 13:42 UTC, Shramkoweb requested changes

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +        <img src="https://via.placeholder.com/1200x509" alt="">
Почему пустой alt?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +      <p>Рассмотрим 5 причин, по которым Седона круче, чем гранд каньон!</p>
Тут явно надо добавить отступ так как эти блоки внутри `section`

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +      <section>
А тут что-то поехало уже в другую сторону

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +      <h2> Преимущества</h2>
```suggestion
      <h2>Преимущества</h2>
```

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +          <img src="https://via.placeholder.com/800x256" alt="">
почему пустой alt?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +течёт своя жизнь</p>
Форматирование - что то тут не красиво все поехало)

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +      <ul>
Список из одного елемента?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +          <h2>Жильё</h2>
Если я все правильно понял то прошлый блок был Преимущества и он был h2 - а это конкретно каждое из преимуществ. Тогда они должны быть внутри этой же секции и h3 ?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +производства!</p>
Форматирвание

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +вы осмелитесь</p>
Форматирование - почему текст в 2 строчки?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +      <h3>Небольшая площадь</h3>
Формтирование

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +
?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +          <a href="blank.html">#VISITSEDONA</a><br>
Зачем тут `<br> `?

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +
Пустая строка

2021-05-21 13:42 UTC, Shramkoweb commented on index.html
> +        <a href="https://htmlacademy.ru">.html academy</a>
`.html academy ` тут все верно?

2021-05-21 13:52 UTC, Ramz10 commented on index.html
> +          <h2>Жильё</h2>
Там 5 преимуществ, я их в h3 вложил, а это как особенности идёт

2021-05-23 07:36 UTC, Shramkoweb approved these changes

2021-05-23 07:36 UTC, merged