Закончил декор элементы внутренней
htmlacademy-htmlcss/1773559-sedona-31 pull request #11
Opened 2021-06-25 15:44 UTC by Ramz10

2021-06-26 08:05 UTC, Shramkoweb requested changes
:hover на логотип  что-то не ок))
![image](https://user-images.githubusercontent.com/42001531/123506669-232f9680-d66e-11eb-9960-94f7cfc95560.png)
Нет состояний икнопки слишком маленькие в высоту. 
![image](https://user-images.githubusercontent.com/42001531/123506706-52460800-d66e-11eb-8835-624a3bf2b09d.png)

2021-06-26 08:05 UTC, Shramkoweb commented on catalog.html
> +                <li><a href="index.html">Информация</a></li>
нет - это блан. Index у на по клику на логотип и все.

2021-06-26 08:05 UTC, Shramkoweb commented on catalog.html
> +                    >от 0<!--<input type="number" name="min-price" value="0"
Это закоменечено так и надо?)) То про что ты говорил?

2021-06-26 08:05 UTC, Shramkoweb commented on catalog.html
> +                <button class="show-button" type="button">Показать</button>
type="submit" дял кнопки, которая отправляет данные с формы. Это правило всегда

2021-06-26 08:30 UTC, Ramz10 commented on catalog.html
> +                    >от 0<!--<input type="number" name="min-price" value="0"
да, я про это говорил))

2021-06-26 08:31 UTC, Ramz10 commented on catalog.html
> +                <button class="show-button" type="button">Показать</button>
у меня причем было нормально, я потом неправильно сделал ,

2021-06-27 14:01 UTC, Shramkoweb approved these changes

2021-06-27 14:01 UTC, Shramkoweb commented on index.html
> +          <a href="catalog.html" class="main-header-logo">
👍

2021-06-27 14:01 UTC, merged