Модальное окно
htmlacademy-htmlcss/1773559-sedona-31 pull request #12
Opened 2021-06-28 15:04 UTC by Ramz10

2021-06-29 19:08 UTC, Shramkoweb requested changes

2021-06-29 19:08 UTC, Shramkoweb commented on index.html
> +            <p class="number">— №2 —</p>
span ?

2021-06-29 19:08 UTC, Shramkoweb commented on style.css
> +  margin: 0 49px 54px 49px; /* ???? */
/* ???? */ что это?

2021-06-29 19:08 UTC, Shramkoweb commented on style.css
?? мусор

2021-06-29 19:08 UTC, Shramkoweb commented on style.css
> +  /* height: 233px;*/
мусор?

2021-06-30 06:15 UTC, Ramz10 commented on index.html
> +            <p class="number">— №2 —</p>
Если давать span, нижний отступ не работает

2021-06-30 20:10 UTC, Shramkoweb commented on index.html
> +            <p class="number">— №2 —</p>
Ага подумай над решением через CSS. Отступ - это как выглядит что-то, значит оно не должно влиять на верстку)

2021-06-30 20:11 UTC, merged