Второе задание + переделал в конце первое
htmlacademy-htmlcss/1773559-sedona-31 pull request #2
Opened 2021-05-24 07:49 UTC by Ramz10

в конце главной страницы где социальные сети убрал тег h2 из ul

2021-05-24 16:06 UTC, Shramkoweb requested changes

2021-05-24 16:06 UTC, Shramkoweb commented on index-page(2).html
> +<!DOCTYPE html>
index-page(2).html ??))

Это страница каталога гостиниц - catalog.html

2021-05-24 16:06 UTC, Shramkoweb commented on index-page(2).html
> +          <li><a href="blank.html">Гостиницы</a></li>
Мы уже на странице каталога Гостиницы - следовательно тут a будет без href

2021-05-24 16:06 UTC, Shramkoweb commented on index-page(2).html
> +      <h1>Седона</h1>
Эта страница уже каталог гостинниц - а не просто Седона

2021-05-24 16:06 UTC, Shramkoweb commented
@Ramz10 в задании сказано 3. Разметка внутренней страницы
А почему тут верстка главной?

2021-05-25 16:38 UTC, Shramkoweb requested changes

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +          <input type="range" min="0" max="3000">
Насколько я помню - потом мы сделаем кастом ренж. Но на время пойдет

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +              <li></li>
пустые теги? Что ты тут планировал?

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +            <a href="blank.html">
А почему в ссылке и картинка и заголовок?

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +              Мотель от 3000 ₽
![image](https://user-images.githubusercontent.com/42001531/119535397-9ce31480-bd90-11eb-9e3f-c8ba5a3e2ef4.png)
А в дизайне похоже на dl & dt список

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +      <section>
div

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +      <section>
div

2021-05-25 16:38 UTC, Shramkoweb commented on catalog.html
> +      <section>
Откуда тут section - или вам в лекции так рссказали?

2021-05-25 16:43 UTC, Ramz10 commented on catalog.html
> +              <li></li>
пустые теги это звездочки в планах

2021-05-25 16:47 UTC, Shramkoweb commented on catalog.html
> +              <li></li>
Хорошо пускай пока будут - но я бы впихнул туда контент 
5 звездочек значит 5 спанов

2021-05-25 16:48 UTC, Shramkoweb commented on catalog.html
> +              <li></li>
`    <ul>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
    </ul>`

2021-05-25 16:48 UTC, Shramkoweb commented on catalog.html
> +              <li></li>
А потом уже как-то числа скроем, и покажем звезды

2021-05-25 16:48 UTC, Ramz10 commented on catalog.html
> +      <section>
Да, в лекции так было, даже сейчас открыл проверил
прямо в макете соц сети обозначены section

2021-05-25 16:51 UTC, Ramz10 commented on catalog.html
> +              Мотель от 3000 ₽
Точно!

2021-05-25 16:53 UTC, Ramz10 commented on catalog.html
> +            <a href="blank.html">
не понял тут как делать?
фотку убирать и заголовок оставлять в ссылке?

2021-05-25 17:03 UTC, Shramkoweb commented on catalog.html
> +            <a href="blank.html">
Я бы оставил только заголовок ссылкой

2021-05-25 17:03 UTC, Shramkoweb commented on catalog.html
> +      <section>
ааа тогда ок))

2021-05-26 19:54 UTC, Shramkoweb approved these changes

2021-05-26 19:54 UTC, merged