Графика
htmlacademy-htmlcss/1773559-sedona-31 pull request #3
Opened 2021-05-28 12:55 UTC by Ramz10

2021-05-28 18:36 UTC, Shramkoweb requested changes

2021-05-28 18:36 UTC, Shramkoweb commented on catalog.html
> +          <img src="img/images/logo_htmlacademy.svg" witdh="115" height="33" alt="логотип HTML Academy">
Тире)

2021-05-28 18:36 UTC, Shramkoweb commented on index.html
> +            alt="Логотип города Седона"
```suggestion
            alt="Логотип сайта Седона"
```

2021-05-28 18:36 UTC, Shramkoweb commented on index.html
> +          alt="Городок"
Почитай какие писать alt https://weblind.ru/inner.html#image-content

2021-05-28 19:06 UTC, Ramz10 commented on index.html
> +            src="img/images/logo.svg"
Scalable vector graphics, что значит масштабируемая векторная графика. Главная отличительная характеристика, то что не теряет качество при изменении масштаба картинки.

2021-05-28 19:10 UTC, Ramz10 commented on index.html
> +            src="img/images/logo.svg"
Поставил его здесь, потому что при экспорте самый маленький вес был у SVG типа картинки

2021-05-28 19:18 UTC, Ramz10 commented on index.html
> +          alt="Городок"
Я понятия не имею как это описать))
Непонятное фото, размытое. Здание на заднем фоне, на переднем флаг США маленький

2021-05-29 18:37 UTC, Shramkoweb commented on index.html
> +          alt="Городок"
Вот так и пиши, что видишь)) Просто писывай то что на фото изображено

2021-05-29 18:38 UTC, Shramkoweb commented on index.html
> +            src="img/images/logo.svg"
Ага, но svg внутри тега img не скейлиться. И в итоге зачем тогда?

2021-05-29 18:38 UTC, Shramkoweb approved these changes

2021-05-29 18:38 UTC, merged

2021-05-30 09:18 UTC, Ramz10 commented on index.html
> +            src="img/images/logo.svg"
Плохо понял, что значит svg внутри img не склеится

2021-05-30 09:24 UTC, Ramz10 commented on index.html
> +            src="img/images/logo.svg"
А, кажется понял, если SVG, то с ним нельзя взаимодействовать?