Флексы внутренней страницы
htmlacademy-htmlcss/1773559-sedona-31 pull request #9
Opened 2021-06-21 18:05 UTC by Ramz10

2021-06-22 18:49 UTC, Shramkoweb requested changes

2021-06-22 18:49 UTC, Shramkoweb commented on catalog.html
>                  <li><a href="blank.html">Гостиницы</a></li>
Гостиницы - это текущая страница каталог. Убрать с нее href

На главной наоборот проверить, что Гостиницы - ведут на каталог.

2021-06-22 18:49 UTC, Shramkoweb commented on catalog.html
> +                <p class="hotel-img">
Я бы выбрал тут `div` вместо `p`

2021-06-22 18:49 UTC, Shramkoweb commented on catalog.html
> +                  <p>
div

2021-06-22 18:49 UTC, Shramkoweb commented on catalog.html
> +                  <p>
div

2021-06-22 18:49 UTC, Shramkoweb commented on style.css
> +} */
?

2021-06-23 05:21 UTC, Ramz10 commented on catalog.html
> +                <p class="hotel-img">
сделал через p, так как на лайве говорили помню картинки через параграф делать

2021-06-23 08:01 UTC, Shramkoweb approved these changes

2021-06-23 08:01 UTC, merged